-- libca_em组件的配置
rule("libca.em_base")
    on_load(function (target)
        local inc_dir = path.join(os.scriptdir(), "src")
        local src_dir = path.join(inc_dir, "em_base")
        target:add("includedirs", inc_dir)
        target:add("files", path.join(src_dir, "*.c"))
    end)
rule_end()

rule("libca.em_util")
    on_load(function (target)
        local inc_dir = path.join(os.scriptdir(), "src")
        local src_dir = path.join(inc_dir, "em_util")
        target:add("includedirs", inc_dir)
        target:add("files", path.join(src_dir, "*.c"))
    end)
rule_end()

rule("libca.em_shell")
    on_load(function (target)
        local inc_dir = path.join(os.scriptdir(), "src")
        local src_dir = path.join(inc_dir, "em_shell")
        target:add("includedirs", inc_dir)
        target:add("files", path.join(src_dir, "*.c"))
    end)
rule_end()

rule("libca.em_protocol")
    on_load(function (target)
        local inc_dir = path.join(os.scriptdir(), "src")
        local src_dir = path.join(inc_dir, "em_protocol")
        target:add("includedirs", inc_dir)
        target:add("files", path.join(src_dir, "file_transfer.c"))
        target:add("files", path.join(src_dir, "xmodem.c"))
    end)
rule_end()
