target("libca-c-core")
    set_kind("shared")
    add_defines("LIBCA_USE_TEST")
    add_files("*.c")
    remove_files("test-*.c")

target("libca-c-core-test")
    set_kind("binary")
    add_defines("LIBCA_USE_TEST")
    add_files("test-**.c")
    add_files("../test-main.c")
    add_deps("libca-c-core")
    add_links("libca-c-core")
