target("libca.em_motion")
    set_kind("static")
    add_files("*.c")
    add_deps("libca.em_base")

target("test-kin_diff")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_kin_diff.c")
    add_files("kin_diff.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-kin_omni")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_kin_omni.c")
    add_files("kin_omni.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-kin_mecanum")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_kin_mecanum.c")
    add_files("kin_mecanum.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-kin_ackermann")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_kin_ackermann.c")
    add_files("kin_ackermann.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-trapezoidal")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_trapezoidal.c")
    add_files("trapezoidal.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-s_curve")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_s_curve.c")
    add_files("s_curve.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-polynomial")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_polynomial.c")
    add_files("polynomial.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-inverted_pendulum")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_inverted_pendulum.c")
    add_files("inverted_pendulum.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-model_trajectory")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_model_trajectory.c")
    add_files("model_trajectory.c")
    add_files("trapezoidal.c")
    add_files("s_curve.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-pwm_ptz")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_pwm_ptz.c")
    add_files("pwm_ptz.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })
