target("libca.em_motion")
    set_kind("static")
    add_files("*.c")
    add_deps("libca.em_base")

target("test-kin_diff")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_kin_diff.c")
    add_files("kin_diff.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-kin_omni")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_kin_omni.c")
    add_files("kin_omni.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })

target("test-kin_mecanum")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("test_kin_mecanum.c")
    add_files("kin_mecanum.c")
    add_deps("libca.em_base")
    add_includedirs(".", { public = true })
