target("StringTest")
    set_kind("binary")
    add_files("StringTest.cpp")
    add_files("../String.cpp")
    add_includedirs("../")
    add_packages("doctest")

target("ResultTest")
    set_kind("binary")
    add_files("ResultTest.cpp")
    add_includedirs("../")
    add_packages("doctest")
