target("ca-c-container")
    set_kind("static")
    add_files("*.c")
    remove_files("test-*.c")

target("ca-c-container-test")
    set_kind("binary")
    add_files("test-*.c")
    add_files("../test-main.c")
    add_defines("LIBCA_USE_TEST")
    add_deps("ca-c-container")
    add_links("ca-c-container")
    add_deps("ca-c-core")
    add_links("ca-c-core")
