target("ca-c-event")
    set_kind("shared")
    add_files("*.c")
    remove_files("test-*.c")

target("ca-c-event-test")
    set_kind("binary")
    add_defines("LIBCA_USE_TEST")
    add_files("test-**.c")
    add_files("../test-main.c")
    add_deps("ca-c-core")
    add_links("ca-c-core")
