-- libca.resources：嵌入资源库（清单驱动的目录树只读嵌入）。
--
-- 组成：
--   1. rule("libca.resources.embed")：构建期把挂载清单(*.resources)中的
--      目录树生成为 constexpr 资源头嵌入二进制（如 exe 字符串表/小文件）。
--      用法：
--        add_files("resources/all.resources", {rules = "libca.resources.embed"})
--      清单为 UTF-8 文本："名称=目录"（# 注释；目录相对清单所在目录；
--      一个清单可声明多个挂载，bundle 隔离）。
--   2. target("libca_resources")：运行时（查找/迭代/自注册，header-only）。
--   3. target("libca_resources_unittest")：带嵌入 fixture 的端到端覆盖。
--
-- 构建期校验（直接报错）：
--   - 挂载名匹配 ^[a-z][a-z0-9_]*$，同清单内不可重复
--   - 单文件上限 1 MiB（constexpr 方案；更大文件待 obj 嵌入方案）
--   - 禁止目录穿越（防"路径字节注入"）；'\' 统一归一为 '/'
--   - 跨挂载同路径合法（bundle 隔离，不会自动合并或抢占）

rule("libca.resources.embed")
    set_extensions(".resources")
    add_orders("libca.resources.embed", "c++.build.modules.builder")
    on_preparecmd_file(function (target, batchcmds, sourcefile, opt)
        local suffix = target:name():gsub("[^%w]", "_")

        -- 解析 资源清单:name=dir(相对清单目录)，边解析边校验保证确定性 与
        local manifestdir = path.directory(sourcefile)
        local byname = {}
        local mounts = {}
        for line in io.readfile(sourcefile):gmatch("[^\r\n]+") do
            line = line:match("^%s*(.-)%s*$")
            if #line > 0 and line:sub(1, 1) ~= "#" then
                local eq = line:find("=", 1, true)
                assert(eq, "resources manifest expects 'name=dir', got: " .. line)
                local name = line:sub(1, eq - 1):match("^%s*(.-)%s*$")
                local dir = line:sub(eq + 1):match("^%s*(.-)%s*$"):gsub("\\", "/")
                assert(name:match("^[a-z][a-z0-9_]*$"),
                       "resources mount name must match ^[a-z][a-z0-9_]*$: " .. tostring(name))
                assert(byname[name] == nil, "duplicate resources mount name: " .. name)
                if not path.is_absolute(dir) then
                    dir = path.join(manifestdir, dir)
                end
                assert(os.isdir(dir),
                       "resources mount dir does not exist (" .. name .. "): " .. dir)
                byname[name] = true
                table.insert(mounts, {name = name, dir = dir})
            end
        end
        assert(#mounts > 0, "resources manifest declares no mounts: " .. sourcefile)
        table.sort(mounts, function (a, b) return a.name < b.name end)

        -- 收集 空间全部挂载点的文件条目:第一遍先收集再剔除 目录
        -- 允许跨挂载同路径合法(bundle 隔离)；文件内容在第二遍读取。 与
        local MAX_FILE_BYTES = 1024 * 1024
        local depfiles = {sourcefile}
        local bundles = {}   -- {name=..., entries={{path,file,size},...}}
        for _, mount in ipairs(mounts) do
            local entries = {}
            for _, file in ipairs(os.filedirs(path.join(mount.dir, "**"))) do
                -- "**" 同时含子目录本身;子目录不是文件则跳过,自然剔除空目录
                if not os.isdir(file) then
                    local rel = path.relative(file, mount.dir):gsub("\\", "/")
                    table.insert(entries, {path = "/" .. rel, file = file})
                end
            end
            -- 按字节序排序,生成期定序,查询时二分(string_view 比较同语义)。
            table.sort(entries, function (a, b) return a.path < b.path end)
            for _, e in ipairs(entries) do
                local data = assert(io.readfile(e.file, {encoding = "binary"}),
                                    "cannot read resource file: " .. e.file)
                assert(#data <= MAX_FILE_BYTES,
                       "resource file exceeds 1 MiB constexpr limit (" .. #data ..
                       " bytes): " .. e.file ..
                       "\n(large files need a future obj-based embedding scheme)")
                e.size = #data
                table.insert(depfiles, e.file)
            end
            table.insert(depfiles, mount.dir)
            table.insert(bundles, {name = mount.name, entries = entries})
        end

        -- 生成 C++ 字符串字面量转义(\ 和 ")。
        local function cppstr(s)
            return '"' .. s:gsub('[\\"]', "\\%1") .. '"'
        end

        -- 输出 生成头:每挂载一个 数据区 + 条目表 + Bundle + Registrar 常量
        local out = {
            "// Generated by rule libca.resources.embed. Do not edit.",
            "#pragma once",
            "",
            "#include <libca/resources/resources.hpp>",
            "",
            "namespace ca::resources::gen {",
            "",
        }
        for _, bundle in ipairs(bundles) do
            local total = 0
            for _, e in ipairs(bundle.entries) do
                total = total + e.size
            end
            out[#out + 1] = "// 挂载 mount '" .. bundle.name .. "': " ..
                            #bundle.entries .. " file(s), " .. total .. " byte(s) 总量"
            if #bundle.entries > 0 then
                for idx, e in ipairs(bundle.entries) do
                    if e.size > 0 then
                        local sym = "kResData_" .. suffix .. "_" .. bundle.name .. "_" .. idx
                        local data = assert(io.readfile(e.file, {encoding = "binary"}),
                                            "cannot read resource file: " .. e.file)
                        out[#out + 1] = "inline constexpr unsigned char " .. sym .. "[] = {"
                        local row = {}
                        for i = 1, e.size do
                            row[#row + 1] = string.format("0x%02x", data:byte(i))
                            if #row == 32 then
                                out[#out + 1] = "    " .. table.concat(row, ", ") .. ","
                                row = {}
                            end
                        end
                        if #row > 0 then
                            out[#out + 1] = "    " .. table.concat(row, ", ") .. ","
                        end
                        out[#out + 1] = "};"
                    end
                end
                out[#out + 1] =
                    "inline constexpr ca::resources::RawEntry kResEntries_" .. suffix ..
                    "_" .. bundle.name .. "[] = {"
                for idx, e in ipairs(bundle.entries) do
                    if e.size > 0 then
                        local sym = "kResData_" .. suffix .. "_" .. bundle.name .. "_" .. idx
                        out[#out + 1] = "    {" .. cppstr(e.path) .. ", " .. sym ..
                                        ", sizeof(" .. sym .. ")},"
                    else
                        out[#out + 1] = "    {" .. cppstr(e.path) .. ", nullptr, 0},"
                    end
                end
                out[#out + 1] = "};"
                local esym = "kResEntries_" .. suffix .. "_" .. bundle.name
                out[#out + 1] =
                    "[[maybe_unused]] inline constexpr ca::resources::Bundle kResBundle_" ..
                    suffix .. "_" .. bundle.name .. "{" .. esym ..
                    ", sizeof(" .. esym .. ") / sizeof(" .. esym .. "[0])};"
            else
                out[#out + 1] =
                    "[[maybe_unused]] inline constexpr ca::resources::Bundle kResBundle_" ..
                    suffix .. "_" .. bundle.name .. "{nullptr, 0};"
            end
            out[#out + 1] =
                "[[maybe_unused]] inline const ca::resources::Registrar kResRegister_" ..
                suffix .. "_" .. bundle.name .. "{\"" .. bundle.name ..
                "\", kResBundle_" .. suffix .. "_" .. bundle.name .. "};"
            out[#out + 1] = ""
        end
        out[#out + 1] = "}   // namespace ca::resources::gen"
        out[#out + 1] = ""

        -- 输出 头文件(public includedir 同 libi18n 模式)+ 依赖清单 依赖
        -- 生成头是 UTF-8 路径字面量,MSVC 需显式按 UTF-8 编译。
        if is_plat("windows") then
            target:add("cxflags", "/utf-8", {tools = "cl"})
        end
        local headerdir = path.join(target:autogendir(), "rules", "libca_resources", "embed")
        if not os.isdir(headerdir) then
            os.mkdir(headerdir)
        end
        target:add("includedirs", headerdir, {public = true})

        local headerfile = path.join(headerdir, "resources_" .. suffix .. ".generated.hpp")
        local content = table.concat(out, "\n")
        local existing = os.isfile(headerfile) and io.readfile(headerfile) or nil
        if existing ~= content then
            io.writefile(headerfile, content)
        end
        batchcmds:add_depfiles(depfiles)
        batchcmds:set_depmtime(os.mtime(headerfile))
        batchcmds:set_depcache(target:dependfile(headerfile))
    end)

-- header-only：状态为 function-local static，静态初始化完成后各接口可并发调用。
target("libca_resources")
    set_kind("headeronly")
    set_group("libs")

    add_deps("libca_core")
    add_headerfiles("src/(libca/resources/*.hpp)")
    add_includedirs("src", {public = true})

-- 端到端单测：本 target 自带嵌入资源 fixture(crt/extra)，覆盖查找/
-- 迭代/过滤/隔离/自注册全语义；fixture 含嵌套目录、UTF-8 文件名与
-- 二进制小文件、空目录（应被丢弃）。
target("libca_resources_unittest")
    set_kind("binary")
    set_default(false)
    set_group("libs/test")

    add_deps("libca_resources")
    add_packages("gtest")
    add_files("unittest/main.cpp")
    add_files("unittest/*_test.cpp")
    add_files("unittest/resources/all.resources", {rules = "libca.resources.embed"})
    -- 依赖 static 变量的自动注册，binary 直接链接即可（同 libi18n_unittest 模式）。
    add_links("libca_core")
    if is_plat("windows") then
        add_cxflags("/utf-8", {tools = "cl"})
    end
