target("ca-em_protocol")
    set_kind("static")
    set_group("em")
    
    add_files("**.c")
    remove_files("test-*.c")
    add_includedirs(".", { public = true })
    add_deps("ca-em_base")
    add_deps("ca-em_util")

-- target("test-xmodem")
--     set_kind("binary")
--     add_rules("em_test", { test_enable = true, use_default_main = true })
--     add_files("xmodem.c")
--     add_deps("ca-em_base", "ca-em_util")

target("test-dummy")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_files("dummy.c")
    add_deps("ca-em_base", "ca-em_util")
