local em_dstream_test_dir = "$(projectdir)/tests/em_dstream"

-- ringbuffer的单元测试
target("test-ring_buffer")
    set_kind("binary")
    add_includedirs(".", em_dstream_test_dir)
    add_files("ring_buffer.c")
    add_files(path.join(em_dstream_test_dir, "test_ring_buffer.c"))
    add_files(path.join(em_dstream_test_dir, "test_ds_ring_buffer.c"))
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-fixed_buffer")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_dstream_test_dir)
    add_files("fixed_buffer.c", "ds_fixed_buffer.c")
    add_files(path.join(em_dstream_test_dir, "test_fixed_buffer.c"))
    add_files(path.join(em_dstream_test_dir, "test_ds_fixed_buffer.c"))
    add_deps("libca.em_base")

target("test-pingpong_buffer")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_dstream_test_dir)
    add_files("pingpong_buffer.c", path.join(em_dstream_test_dir, "test_pingpong_buffer.c"))
    add_deps("libca.em_base")

target("test-delimiter_parser")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_dstream_test_dir)
    add_files("delimiter_parser.c", path.join(em_dstream_test_dir, "test_delimiter_parser.c"))
    add_deps("libca.em_base")

target("test-length_parser")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_dstream_test_dir)
    add_files("length_parser.c", path.join(em_dstream_test_dir, "test_length_parser.c"))
    add_deps("libca.em_base")
