-- 嵌入式实用工具库
target("libca.em_util")
    set_kind("object")
    set_group("em")
    add_files("**.c")
    add_deps("libca.em_base")
    -- link libm for math functions (tanf, sqrtf, etc.)
    -- add_syslinks("m")

target("libca.em_util_static")
    set_kind("static")
    set_group("em")
    add_files("**.c")
    add_deps("libca.em_base")

local em_util_test_dir = "$(projectdir)/tests/em_util"

target("test-crc")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("crc.c", path.join(em_util_test_dir, "test_crc.c"))
    add_deps("libca.em_base")

target("test-endian_util")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("endian_util.c", path.join(em_util_test_dir, "test_endian_util.c"))
    add_deps("libca.em_base")

target("test-pid")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("pid.c", path.join(em_util_test_dir, "test_pid.c"))
    add_deps("libca.em_base")

target("test-filter")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("filter.c", path.join(em_util_test_dir, "test_filter.c"))
    add_deps("libca.em_base")
    -- link libm for math functions (tanf, sqrtf, etc.)
    -- add_syslinks("m")

-- 嵌入式容器库
target("libca.em_collection")
    set_kind("static")
    set_group("em")
    add_files("**.c")
    remove_files("test-*.c")
    add_deps("libca.em_base")

target("test-doubly_linked_list")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("doubly_linked_list.c", path.join(em_util_test_dir, "test_doubly_linked_list.c"))
    add_deps("libca.em_base")

target("test-queue")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("queue.c", path.join(em_util_test_dir, "test_queue.c"))
    add_files("doubly_linked_list.c")
    add_deps("libca.em_base")

target("test-stack")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("stack.c", path.join(em_util_test_dir, "test_stack.c"))
    add_deps("libca.em_base")

target("test-singly_list")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("singly_list.c", path.join(em_util_test_dir, "test_singly_list.c"))
    add_deps("libca.em_base")

target("test-lifo")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("lifo.c", path.join(em_util_test_dir, "test_lifo.c"))
    add_deps("libca.em_base")

target("test-doubly_list")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("doubly_list.c", path.join(em_util_test_dir, "test_doubly_list.c"))
    add_deps("libca.em_base")

-- mem_view 单元测试
target("test-mem_view")
    set_kind("binary")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_includedirs(".", em_util_test_dir)
    add_files("mem_view.c", path.join(em_util_test_dir, "test_mem_view.c"))
    add_deps("libca.em_base")

