target("ringbuffer")
    set_kind("static")
    add_includedirs(".")
    add_files("libca/ringbuffer.c")

target("ringbuffer-test")
    set_kind("binary")
    add_files("libca/test_ringbuffer.c")
    add_includedirs(".")
    add_deps("ringbuffer")
    add_links("ringbuffer")

target("doubly_linked_list")
    set_kind("static")
    add_includedirs(".")
    add_files("libca/doubly_linked_list.c")

target("doubly_linked_list-test")
    set_kind("binary")
    add_files("libca/test_doubly_linked_list.c")
    add_includedirs(".")
    add_deps("doubly_linked_list")
    add_links("doubly_linked_list")

target("stack")
    set_kind("static")
    add_includedirs(".")
    add_files("libca/stack.c")

target("stack-test")
    set_kind("binary")
    add_files("libca/test_stack.c")
    add_includedirs(".")
    add_deps("stack")
    add_links("stack")

target("queue")
    set_kind("static")
    add_includedirs(".")
    add_files("libca/queue.c")
    add_deps("doubly_linked_list")
    add_links("doubly_linked_list")

target("queue-test")
    set_kind("binary")
    add_files("libca/test_queue.c")
    add_includedirs(".")
    add_deps("queue")
    add_links("queue")
    add_deps("doubly_linked_list")
    add_links("doubly_linked_list")

target("string")
    set_kind("static")
    add_includedirs(".")
    add_files("libca/string.c")

target("string-test")
    set_kind("binary")
    add_files("libca/test_string.c")
    add_includedirs(".")
    add_deps("string")
    add_links("string")
