add_includedirs("$(projectdir)/src/c")

set_languages("c99")

-- includes("libca/core")
-- includes("libca/container")
-- includes("libca/algorithm")
-- includes("libca/event")
-- includes("libca/log")
-- includes("libca/network")
-- includes("libca/concurrency")

-- target("ringbuffer")
--     set_kind("static")
--     add_includedirs(".")
--     add_files("libca/container/ringbuffer.c")

-- target("ringbuffer-test")
--     set_kind("binary")
--     add_files("libca/container/test_ringbuffer.c")
--     add_includedirs(".")
--     add_deps("ringbuffer")
--     add_links("ringbuffer")

-- target("doubly_linked_list")
--     set_kind("static")
--     add_includedirs(".")
--     add_files("libca/container/doubly_linked_list.c")

-- target("doubly_linked_list-test")
--     set_kind("binary")
--     add_files("libca/container/test_doubly_linked_list.c")
--     add_includedirs(".")
--     add_deps("doubly_linked_list")
--     add_links("doubly_linked_list")

-- target("stack")
--     set_kind("static")
--     add_includedirs(".")
--     add_files("libca/container/stack.c")

-- target("stack-test")
--     set_kind("binary")
--     add_files("libca/container/test_stack.c")
--     add_includedirs(".")
--     add_deps("stack")
--     add_links("stack")

-- target("queue")
--     set_kind("static")
--     add_includedirs(".")
--     add_files("libca/container/queue.c")
--     add_deps("doubly_linked_list")
--     add_links("doubly_linked_list")

-- target("queue-test")
--     set_kind("binary")
--     add_files("libca/container/test_queue.c")
--     add_includedirs(".")
--     add_deps("queue")
--     add_links("queue")
--     add_deps("doubly_linked_list")
--     add_links("doubly_linked_list")

-- target("string")
--     set_kind("static")
--     add_includedirs(".")
--     add_files("libca/core/string.c")

-- target("string-test")
--     set_kind("binary")
--     add_files("libca/core/test_string.c")
--     add_includedirs(".")
--     add_deps("string")
--     add_links("string")

-- target("test-module")
--     set_kind("binary")
--     add_files("libca/core/test.c")
--     add_includedirs(".")
