target("libca.em_format")
    set_kind("object")
    set_group("em")
    add_files("format.c")
    add_deps("libca.em_base")

target("libca.em_format_static")
    set_kind("static")
    set_group("em")
    add_files("format.c")
    add_deps("libca.em_base")

local em_format_test_dir = "$(projectdir)/tests/em_format"

-- format 的单元测试（默认特性开关）
target("test-format")
    set_kind("binary")
    add_includedirs(".", em_format_test_dir)
    add_files("format.c", path.join(em_format_test_dir, "test_format.c"))
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-format-float-fixed")
    set_kind("binary")
    add_includedirs(".", em_format_test_dir)
    add_files("format.c", path.join(em_format_test_dir, "test_format.c"))
    add_defines("FMT_ENABLE_FLOAT=1")
    add_defines("FMT_ENABLE_WIDTH_PRECISION=1")
    add_defines("FMT_ENABLE_HEX=1")
    add_defines("FMT_FLOAT_MODE=FMT_FLOAT_MODE_FIXED")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-format-float-simple")
    set_kind("binary")
    add_includedirs(".", em_format_test_dir)
    add_files("format.c", path.join(em_format_test_dir, "test_format.c"))
    add_defines("FMT_ENABLE_FLOAT=1")
    add_defines("FMT_ENABLE_WIDTH_PRECISION=1")
    add_defines("FMT_ENABLE_HEX=1")
    add_defines("FMT_FLOAT_MODE=FMT_FLOAT_MODE_SIMPLE")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")

target("test-format-float-normal")
    set_kind("binary")
    add_includedirs(".", em_format_test_dir)
    add_files("format.c", path.join(em_format_test_dir, "test_format.c"))
    add_defines("FMT_ENABLE_FLOAT=1")
    add_defines("FMT_ENABLE_WIDTH_PRECISION=1")
    add_defines("FMT_ENABLE_HEX=1")
    add_defines("FMT_FLOAT_MODE=FMT_FLOAT_MODE_NORMAL")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")
