target("ca")
    -- set_kind("binary")
    set_kind("$(kind)")
    add_includedirs("../include")
    add_files("**.cpp")
    -- set_basename("ca")
    -- add_packages("spdlog")
    add_links("mysqlclient")
target_end()

