target("libca.em_ota")
    set_kind("static")
    add_files("partition.c")
    add_deps("libca.em_base")
    add_includedirs("..", {public = true})

target("test-em_ota")
    set_kind("binary")
    add_files("partition.c")
    add_rules("em_test", { test_enable = true, use_default_main = true })
    add_deps("libca.em_base")
