name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false

    # 参考https://github.com/xmake-io/github-action-setup-xmake的README配置缓存
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: 3.0.5
        actions-cache-folder: '.xmake-cache'

    - name: Configure xmake
      run: xmake config --toolchain=gcc --ccache=y -y

    - name: Build
      run: xmake build -v

    - name: Run tests
      run: xmake test -g em/test -v
